### ISSUE TITLE
Add readme for beacon and ga4gh-legacy alt models

### ISSUE THREAD

**Issue by larrybabb** [ga4gh-gks/variant-representation#2]
Readme.md files are needed for the beacon and ga4gh-legacy folders in the alternative-models folder.

**Comment by mbaudis** [comment]
README added for:

* [Beacon v0.4](https://github.com/ga4gh-gks/variant-representation-model/blob/master/alternative-models/beacon-0.4/README.md)
* [GA4GH legacy](https://github.com/ga4gh-gks/variant-representation-model/blob/master/alternative-models/ga4gh-legacy/README.md)
